Add tesseract build for foxy
ros-industrial/docker pull request #35
Opened 2020-07-08 13:17 UTC by Minipada

I'm adding a build for Foxy for tesseract.

1. I also changed the build arguments since there is no `foxy-perception` tag yet. This follows the work started on https://github.com/ros-industrial-consortium/trajopt_ros/pull/194
2. rviz has been renamed rviz2 on foxy
3. octomap not available on foxy

@mpowelson, you probably want to review this.

2020-07-08 13:26 UTC, mpowelson commented
I'll tag @Levi-Armstrong as well since he was the author of these images.

2020-07-09 20:38 UTC, Levi-Armstrong requested changes

2020-07-09 20:38 UTC, Levi-Armstrong commented on tesseract/Dockerfile
>  ARG ROSDISTRO
Missing `ARG ROS_BASE_TAG` here.

2020-07-10 09:33 UTC, Minipada commented on tesseract/Dockerfile
>  ARG ROSDISTRO
It's already at line 2

2020-07-10 16:27 UTC, Levi-Armstrong commented
@Minipada Also the dockers are not building in CI.

2020-07-10 16:31 UTC, Levi-Armstrong commented
It looks like you cannot pass two args to --build-arg. So need to change the line below removing the --build-arg and change CI to have `--build-arg <ARG1> --build-arg <ARG2>`

https://github.com/ros-industrial/docker/blob/8bee1905322346adc422b0c626ba326efe047b6d/build.sh#L25

2020-07-10 18:33 UTC, Levi-Armstrong approved these changes

2020-07-10 18:33 UTC, merged