Added Caffe docker files
ros-industrial/docker pull request #4
Opened 2017-06-09 18:12 UTC by akgoins

2017-06-09 18:25 UTC, AustinDeric requested changes
looks good, minor changes!

2017-06-09 18:25 UTC, AustinDeric commented on caffe/indigo/Dockerfile
> +LABEL maintainer caffe-maint@googlegroups.com
Can you change the maintainer on both of these to you or I?  Otherwise these look good.

2017-06-09 18:25 UTC, AustinDeric commented on caffe/indigo/Dockerfile
> +#1.0
lets make sure to note the difference

2017-06-09 18:31 UTC, AustinDeric commented
If this caffe is the CPU version, then lets distinguish that.  Maybe an example is rosindustrial/caffe-cpu:indigo.  Thanks!

2017-06-13 20:06 UTC, akgoins commented on caffe/indigo/Dockerfile
> +#1.0
Do you want the note in the file or do you want me to create an issue?

2017-06-13 20:11 UTC, AustinDeric commented on caffe/indigo/Dockerfile
> +#1.0
I think an issue would give it better visibility but if you want to comment the Dockerfile, that would be great!

2017-06-13 21:36 UTC, akgoins commented
@AustinDeric, changes made.  Please review.

2017-06-14 13:27 UTC, AustinDeric approved these changes

2017-06-14 13:27 UTC, merged